version: '3.8'

services:
  backend:
    image: oteslifar/harmonysync-app:latest
    environment:
      FLASK_SECRET_KEY: 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
    networks:
      - app-network

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    networks:
      - app-network

  caddy:
    image: caddy:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./frontend/dist:/usr/share/caddy/html
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - backend
      - frontend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  caddy_data:
  caddy_config:
