version: '3.8'

services:
  backend:
    image: oteslifar/harmonysync-app:latest
    expose:
      - "5000"
    environment:
      - FLASK_SECRET_KEY=${FLASK_SECRET_KEY} 
      - MONGO_URI=${MONGO_URI}
    networks:
      - app-network
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    expose:
      - "80"
    networks:
      - app-network
    restart: unless-stopped

  caddy:
    image: caddy:2-alpine
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"  # HTTP/3
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./frontend/dist:/usr/share/caddy/html:ro
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - backend
      - frontend
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge

volumes:
  caddy_data:
  caddy_config: