services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/var/www/harmonysync/backend  # Для горячей перезагрузки кода
    environment:
      FLASK_SECRET_KEY: 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
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "4173:4173"
    volumes:
      - ./frontend:/var/www/harmonysync/frontend  # Для горячей перезагрузки кода
    environment:
      VITE_API_URL: http://backend:5000  # Указываем URL бэкенда внутри сети Docker
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
